{
	"version": 1695973856,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/table-sheet0.png",
		"images/books-sheet0.png",
		"images/books2-sheet0.png",
		"images/books2-sheet1.png",
		"images/books2-sheet2.png",
		"images/play-sheet0.png",
		"images/name-sheet0.png",
		"images/best-sheet0.png",
		"images/sound-sheet0.png",
		"images/sound-sheet1.png",
		"images/shado-sheet0.png",
		"images/check-sheet0.png",
		"images/char1-sheet0.png",
		"images/char2-sheet0.png",
		"images/home-sheet0.png",
		"images/shado2-sheet0.png",
		"images/shado2-sheet1.png",
		"images/sound2-sheet0.png",
		"images/gameoverteach-sheet0.png",
		"images/chasb-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite-sheet3.png",
		"images/sprite2-sheet0.png",
		"media/happy3.ogg",
		"media/books collision.ogg",
		"media/collision table.ogg",
		"media/touchbutton.ogg",
		"media/happy.ogg",
		"media/happy1.ogg",
		"media/happy2.ogg",
		"media/spell_01.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}